### ISSUE TITLE
Another component issue

### ISSUE THREAD

**Issue by lyallg** [projectEndings/staticSearch#78] opened 2020-09-30 19:55 UTC
Hi guys,

For BCHT project I tried Martin's route with dvpp project, using svn export to get the code from GitHub and then running with ANT. Getting the code worked fine, but then build fails on:
    [java]   FOUT1170: Failed to read input file:
     [java]   /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch-0.9/xsl/english_stopwords.txt (No
     [java]   such file or directory)

I am tempted to go find the missing file like I did with the other one yesterday and out it there, but the ANT build clears out older version first, so I would have to disable that, and I imagine everything should come down with svn anyway. The error may be further up and something to do with my config file. It is the same one I ran on a different project successfully last night. So I am unsure.

Here is build report. Thanks:

ant searchBCHT
Buildfile: /mnt/c/Users/Gord/Documents/bctextbooks/build.xml

getStaticSearchCode:
     [echo] *********************************
     [echo] Getting the latest version of the staticSearch codebase for the site search.
     [exec] A    staticSearch
     [exec] A    staticSearch/.gitignore
     [exec] A    staticSearch/EDITION
     [exec] A    staticSearch/LICENSE
     [exec] A    staticSearch/README.md
     [exec] A    staticSearch/build.xml
     [exec] A    staticSearch/buildSchema.xml
     [exec] A    staticSearch/configTest.xml
     [exec] A    staticSearch/configTestWorthReading.xml
     [exec] A    staticSearch/config_documentation.xml
     [exec] A    staticSearch/config_emod.xml
     [exec] A    staticSearch/config_moeml.xml
     [exec] A    staticSearch/docs
     [exec] A    staticSearch/docs/buildPlan.md
     [exec] A    staticSearch/docs/doc_chapters.css
     [exec] A    staticSearch/docs/documentation.css
     [exec] A    staticSearch/docs/howDoIGetIt.html
     [exec] A    staticSearch/docs/howDoIUseIt.html
     [exec] A    staticSearch/docs/howDoesItWork.html
     [exec] A    staticSearch/docs/index.html
     [exec] A    staticSearch/docs/schemaSpec.html
     [exec] A    staticSearch/docs/search
     [exec] A    staticSearch/docs/search/dicts
     [exec] A    staticSearch/docs/search/dicts/english_stopwords.xml
     [exec] A    staticSearch/docs/search/dicts/english_words.xml
     [exec] A    staticSearch/docs/search/ssSearch.js
     [exec] A    staticSearch/docs/search/staticSearch_report.html
     [exec] A    staticSearch/docs/searchFacetFeatures.html
     [exec] A    staticSearch/docs/searchPlan.txt
     [exec] A    staticSearch/docs/staticSearch.html
     [exec] A    staticSearch/docs/testSetRequirements.txt
     [exec] A    staticSearch/docs/textSearchFeatures.html
     [exec] A    staticSearch/docs/whatDoesItDo.html
     [exec] A    staticSearch/docs/whyWouldIUseIt.html
     [exec] A    staticSearch/emod
     [exec] A    staticSearch/emod/ARIE1.htm
     [exec] A    staticSearch/emod/BRIT4.htm
     [exec] A    staticSearch/emod/CAMP3.htm
     [exec] A    staticSearch/emod/CHRU1.htm
     [exec] A    staticSearch/emod/CHRY1.htm
     [exec] A    staticSearch/emod/DECE1.htm
     [exec] A    staticSearch/emod/DEVI3.htm
     [exec] A    staticSearch/emod/DIXI2.htm
     [exec] A    staticSearch/emod/EMPO1.htm
     [exec] A    staticSearch/emod/FAME2.htm
     [exec] A    staticSearch/emod/GOLD4.htm
     [exec] A    staticSearch/emod/HEAL2.htm
     [exec] A    staticSearch/emod/HIMA1.htm
     [exec] A    staticSearch/emod/INTE1.htm
     [exec] A    staticSearch/emod/JUSH1.htm
     [exec] A    staticSearch/emod/LOVE8.htm
     [exec] A    staticSearch/emod/METR1.htm
     [exec] A    staticSearch/emod/MONU1.htm
     [exec] A    staticSearch/emod/PECA1.htm
     [exec] A    staticSearch/emod/PIET2.htm
     [exec] A    staticSearch/emod/SCAT1.htm
     [exec] A    staticSearch/emod/SIDE1.htm
     [exec] A    staticSearch/emod/SINU1.htm
     [exec] A    staticSearch/emod/SPEC1.htm
     [exec] A    staticSearch/emod/TEMP3.htm
     [exec] A    staticSearch/emod/TESI1.htm
     [exec] A    staticSearch/emod/TRIU1.htm
     [exec] A    staticSearch/emod/TRIU2.htm
     [exec] A    staticSearch/emod/TRIU3.htm
     [exec] A    staticSearch/emod/TROI1.htm
     [exec] A    staticSearch/emod/VERT2.htm
     [exec] A    staticSearch/jenkins
     [exec] A    staticSearch/jenkins/ss_log_parse_rules
     [exec] A    staticSearch/js
     [exec] A    staticSearch/js/searchTest.html
     [exec] A    staticSearch/js/searchTest.js
     [exec] A    staticSearch/js/ssSearch.js
     [exec] A    staticSearch/lib
     [exec] A    staticSearch/lib/jing-notices
     [exec] A    staticSearch/lib/jing-notices/copying.html
     [exec] A    staticSearch/lib/jing-notices/isorelax.copying.txt
     [exec] A    staticSearch/lib/jing-notices/xerces.copying.txt
     [exec] A    staticSearch/lib/jing.jar
     [exec] A    staticSearch/lib/saxon-he-10.jar
     [exec] A    staticSearch/lib/saxon_docs
     [exec] A    staticSearch/lib/saxon_docs/img
     [exec] A    staticSearch/lib/saxon_docs/img/logo_crop-mid-blue-background.gif
     [exec] A    staticSearch/lib/saxon_docs/img/saxonica_logo.gif
     [exec] A    staticSearch/lib/saxon_docs/index.html
     [exec] A    staticSearch/lib/saxon_docs/saxondocs.css
     [exec] A    staticSearch/lib/saxon_notices
     [exec] A    staticSearch/lib/saxon_notices/JAMESCLARK.txt
     [exec] A    staticSearch/lib/saxon_notices/JLINE2.txt
     [exec] A    staticSearch/lib/saxon_notices/LICENSE.txt
     [exec] A    staticSearch/lib/saxon_notices/THAI.txt
     [exec] A    staticSearch/lib/saxon_notices/UNICODE.txt
     [exec] A    staticSearch/lib/schematron
     [exec] A    staticSearch/lib/schematron/ExtractSchFromRNG-2.xsl
     [exec] A    staticSearch/lib/schematron/ExtractSchFromXSD-2.xsl
     [exec] A    staticSearch/lib/schematron/iso_abstract_expand.xsl
     [exec] A    staticSearch/lib/schematron/iso_dsdl_include.xsl
     [exec] A    staticSearch/lib/schematron/iso_schematron_message_xslt2.xsl
     [exec] A    staticSearch/lib/schematron/iso_schematron_skeleton_for_saxon.xsl
     [exec] A    staticSearch/lib/schematron/iso_svrl_for_xslt2.xsl
     [exec] A    staticSearch/lib/schematron/readme.txt
     [exec] A    staticSearch/lib/schematron/sch-messages-cs.xhtml
     [exec] A    staticSearch/lib/schematron/sch-messages-de.xhtml
     [exec] A    staticSearch/lib/schematron/sch-messages-en.xhtml
     [exec] A    staticSearch/lib/schematron/sch-messages-fr.xhtml
     [exec] A    staticSearch/lib/schematron/sch-messages-nl.xhtml
     [exec] A    staticSearch/lib/schematron/schematron-skeleton-api.htm
     [exec] A    staticSearch/license_BSD.txt
     [exec] A    staticSearch/makeRelease.xml
     [exec] A    staticSearch/schema
     [exec] A    staticSearch/schema/staticSearch.odd
     [exec] A    staticSearch/schema/staticSearch.rng
     [exec] A    staticSearch/schema/staticSearch.sch
     [exec] A    staticSearch/staticSearch.xpr
     [exec] A    staticSearch/stemmers
     [exec] A    staticSearch/stemmers/en
     [exec] A    staticSearch/stemmers/en/ssStemmer.js
     [exec] A    staticSearch/stemmers/en/ssStemmer.xsl
     [exec] A    staticSearch/stemmers/en/ssStemmer.xspec
     [exec] A    staticSearch/stemmers/en/ssStemmerTest.html
     [exec] A    staticSearch/stemmers/en/ssStemmerTest.js
     [exec] A    staticSearch/stemmers/en/ssStemmerTestData.json
     [exec] A    staticSearch/stemmers/identity
     [exec] A    staticSearch/stemmers/identity/ssStemmer.js
     [exec] A    staticSearch/stemmers/identity/ssStemmer.xsl
     [exec] A    staticSearch/test
     [exec] A    staticSearch/test/badthings.html
     [exec] A    staticSearch/test/clues.html
     [exec] A    staticSearch/test/images
     [exec] A    staticSearch/test/images/booze.png
     [exec] A    staticSearch/test/images/crossword.png
     [exec] A    staticSearch/test/images/lookout.svg
     [exec] A    staticSearch/test/index.html
     [exec] A    staticSearch/test/poems
     [exec] A    staticSearch/test/poems/ditty.html
     [exec] A    staticSearch/test/poems/shizukesaya.html
     [exec] A    staticSearch/test/poems/twilight.html
     [exec] A    staticSearch/test/search.html
     [exec] A    staticSearch/test/searchWorthReading.html
     [exec] A    staticSearch/test/tables
     [exec] A    staticSearch/test/tables/booze.html
     [exec] A    staticSearch/test/tables/decade_year.html
     [exec] A    staticSearch/test/test_stopwords.txt
     [exec] A    staticSearch/utilities
     [exec] A    staticSearch/utilities/get_emod_texts.xsl
     [exec] A    staticSearch/xsl
     [exec] A    staticSearch/xsl/create_config_xsl.xsl
     [exec] A    staticSearch/xsl/create_reports.xsl
     [exec] A    staticSearch/xsl/create_ssStems.xsl
     [exec] A    staticSearch/xsl/english_stopwords.txt
     [exec] A    staticSearch/xsl/english_words.txt
     [exec] A    staticSearch/xsl/functions.xsl
     [exec] A    staticSearch/xsl/functions.xspec
     [exec] A    staticSearch/xsl/json.xsl
     [exec] A    staticSearch/xsl/keats_stopwords.txt
     [exec] A    staticSearch/xsl/makeSearchPage.xsl
     [exec] A    staticSearch/xsl/sample_search.html
     [exec] A    staticSearch/xsl/spiff_up_documentation.xsl
     [exec] A    staticSearch/xsl/split_documentation.xsl
     [exec] A    staticSearch/xsl/tokenize.xsl
     [exec] Exported revision 868.

buildStaticSearch:
     [echo] *********************************
     [echo] Building static search...

init:
     [echo] Initializing...
     [echo] Deleting old products...
     [echo] Creating new static search directory: /mnt/c/Users/Gord/Documents/bctextbooks/site/search/
    [mkdir] Created dir: /mnt/c/Users/Gord/Documents/bctextbooks/site/search

validate:
     [echo] Validating /mnt/c/Users/Gord/Documents/bctextbooks/site for well-formedness
[xmlvalidate] 16 file(s) have been successfully validated.
     [echo] Validating /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml against the staticSearch schema...
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:24:68: error: attribute "xpath" not allowed here; expected attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:24:68: error: element "rule" missing required attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:27:166: error: attribute "xpath" not allowed here; expected attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:27:166: error: element "rule" missing required attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:30:71: error: attribute "xpath" not allowed here; expected attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:30:71: error: element "rule" missing required attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:33:84: error: attribute "xpath" not allowed here; expected attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:33:84: error: element "rule" missing required attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:43:71: error: attribute "xpath" not allowed here; expected attribute "match" or "type"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:43:71: error: element "exclude" missing required attribute "match"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:46:88: error: attribute "xpath" not allowed here; expected attribute "match" or "type"
     [exec] /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml:46:88: error: element "exclude" missing required attribute "match"
     [exec] Result: 1

config:
     [echo] Creating configuration file...
     [java] Creating configuration file from /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/../config_staticSearch.xml
     [java] $searchFile: site/search.html
     [java] $recurse: false
     [java] $phrasalSearch: true
     [java] $createContexts: true
     [java] $maxKwicsToHarvest: 3
     [java] $maxKwicsToShow: 3
     [java] $totalKwicLength: 15
     [java] $kwicTruncateString: ...
     [java] $verbose: true
     [java] $stopwordsFile: staticSearch-0.9/xsl/english_stopwords.txt
     [java] $dictionaryFile: staticSearch-0.9/xsl/english_words.txt
     [java] $indentJSON: false
     [java] $outputFolder: search
     [java] Getting schema from file:/mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/schema/staticSearch.odd
     [java] Error evaluating (fn:unparsed-text(...)) in xsl:for-each/@select on line 504 column 81 of create_config_xsl.xsl:
     [java]   FOUT1170: Failed to read input file:
     [java]   /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch-0.9/xsl/english_stopwords.txt (No
     [java]   such file or directory)
     [java] Failed to read input file

BUILD FAILED
/mnt/c/Users/Gord/Documents/bctextbooks/build.xml:492: The following error occurred while executing this line:
/mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/build.xml:167: Java returned: 2

**Comment by martindholmes** [comment] 2020-09-30 20:01
Are you using the dev branch? Did you clear out all your old data before running the export? I know the DVPP build is working fine with this approach.

**Comment by joeytakeda** [comment] 2020-09-30 20:04
I think the issue is with your config file. The search is looking for stuff in:

```
 /mnt/c/Users/Gord/Documents/bctextbooks/staticSearch-0.9/xsl/english_stopwords.txt
```

but it looks like your staticSearch is just called `staticSearch`. So you'll need to update your config to use that.

Plus, it looks like your config is using the old syntax of `@xpath`, which was switched to `@match` between version 0.9 and now. Following 1.0, we shouldn't have any more backwards incompatible things, but it's good to make sure that your config is totally valid.

**Comment by lyallg** [comment] 2020-09-30 20:05
Right. Duh. It's the opposite of the same issue I had yesterday morning.

**Comment by lyallg** [comment] 2020-09-30 20:16
I got a little further, then some <eof> error I commented out <rules> and <excludes> for now because I don't think I need them, but now it seems I have some settings issue. Again, the search build worked last night when downloaded from this site directly without svn or git. This looks like I am using wrong Saxon? I am pretty sure I use the same one on other project: 

tokenize:
     [echo] Creating tokenized XHTML files...
     [java] Warning at xsl:function on line 247 column 66 of ssStemmer.xsl:
     [java]   SXWN9011: Memo functions are not available in Saxon-HE: saxon:memo-function attribute ignored
     [java] Static error at char 13 in xsl:variable/@select on line 322 column 90 of tokenize.xsl:
     [java]   XPTY0004: The required item type of the value of variable $absPath is xs:string; supplied
     [java]   expression (fn:resolve-uri(...)) has item type xs:anyURI
     [java] Errors were reported during stylesheet compilation

BUILD FAILED
/mnt/c/Users/Gord/Documents/bctextbooks/build.xml:492: The following error occurred while executing this line:
/mnt/c/Users/Gord/Documents/bctextbooks/staticSearch/build.xml:187: Java returned: 2

**Comment by joeytakeda** [comment] 2020-09-30 20:21
It looks like you have a wrapper build around the staticSearch build, right? If that's the case, how are you calling the staticSearch build?

Here is what I do for the WEA (from a file called build.xml) 
```
    <target name="createStaticSearch">
        <ant antfile="code/staticSearch/code/build.xml" inheritall="false" target="allButValidate">
            <property name="config" value="../config.xml"/>
            <property name="headless" value="true"/>
        </ant>
    </target>
```

Note the `@inheritall` attribute: if you have a property named `saxon` in the wrapper build, then that will override the `saxon` property in staticSearch. We should _probably_ prefix all of our property names to try and avoid that collision, though.

**Comment by lyallg** [comment] 2020-09-30 20:29
Ok. Great. That seems to be working! Thanks both. Linux subsystems takes a long time, so I will go have lunch and see how long this one takes. Much appreciated.

**Comment by lyallg** [comment] 2020-09-30 20:30
Hey! That one only took 2 minutes!

**Comment by joeytakeda** [comment] 2020-09-30 20:57
Excellent! Since this issue seems to be fixed, I'm going to close it.

**Closed by joeytakeda** 2020-09-30 20:57 UTC
