### ISSUE TITLE
Tokenize Step Fails - Problem With Filepaths on Windows

### ISSUE THREAD

**Issue by tklampfl** [projectEndings/staticSearch#56] opened 2020-05-29 08:11 UTC
The tokenize step fails with the error message:

>     [java] Error in xsl:result-document/@href on line 164 column 64 of tokenize.xsl:
>     [java]   XTDE1490  Cannot write more than one result document to the same URI:
>     [java]   file:/temp/dita-example-2/out/xhtml/search/temp/_tokenized.html
>     [java]      invoked by xsl:for-each at file:/C:/Temp/staticSearch/xsl/tokenize.xsl#95
>     [java]   In template rule with match="/" on line 91 of tokenize.xsl
>     [java] Cannot write more than one result document to the same URI: file:/temp/dita-example-2/out/xhtml/search/temp/_tokenized.html

The problem seems to be following line in ```tokenize.xsl```:

<xsl:variable name="relativeUri" select="substring-after($uri,$collectionDir) => replace('^(/|\\)','')" as="xs:string"/>
The value of ```$uri``` is ```file:/C:/temp/dita-example-2/out/xhtml/1890-05-22_01.html```
The value of ```$collectionDir``` is ```file:/temp/dita-example-2/out/xhtml```
The ```substring-after()``` delivers an empty string. Therefore the filename is always the same.

If you need further information do not hesitate to contact me.
Thank you for your help and your project.

**Comment by martindholmes** [comment] 2020-05-29 13:41
@tklampfl Yes, we have a ticket for that already:

 https://github.com/projectEndings/staticSearch/issues/33

It's been outstanding for so long because neither of us uses Windows, nor do the build servers for any of our products, so it's hard to debug. If you use XSLT on Windows a lot, maybe you could help?

**Comment by martindholmes** [comment] 2020-07-04 13:07
Closing this as a duplicate of #33; copying the report detail there.

**Closed by martindholmes** 2020-07-04 13:07 UTC
Labels: duplicate
