### ISSUE TITLE
Tokenizer breaks words on the combining diacritic U+308 (combining diaeresis)

### ISSUE THREAD

**Issue by wsalesky** [projectEndings/staticSearch#164] opened 2021-07-30 15:19 UTC
We have found that the current tokenizer treats the Syriac plural marker (which uses Unicode U+0308) as a word-break, is there a way I can customize the tokenizer to deal with this? Where should I be looking in the code?

**Comment by martindholmes** [comment] 2021-07-30 17:08
This just seems like a bug to me. A combining diaeresis should not be causing a token break. Can you provide a very small sample file we can use to test the problem?

**Comment by wsalesky** [comment] 2021-07-30 17:49
Sure. Here is an HTML file demonstrating the issue:
https://www.medievalmideast.org/place/10018.html
Syriac plural marker: ̈
Unicode: U+0308

Searching the following term does not find a match: ܕܙܝ̈ܬܐ
 but this (the part of the word before the plural marker) does find a match: ܕܙܝ

Thanks for looking into this. Let me know if you need anything else from me to help with the debugging. 
I'm attaching a version of the HTML to the comment. 
[10018.html.zip](https://github.com/projectEndings/staticSearch/files/6909242/10018.html.zip)

**Comment by martindholmes** [comment] 2021-07-30 21:40
Thanks Winona. The first thing for us to check is whether this problem occurs with ltr languages too, where the combining diaeresis is also common. I'll start by adding that, and a test for it, to our test suite. If it works OK with ltr but not with rtl, we've gone something a bit weird going on. @joeytakeda Do you remember anything special about combining diacritics and tokenizing?

**Comment by wsalesky** [comment] 2021-07-30 21:42
@martindholmes let me know if you need any other data for testing. I have a lot of both rtl and ltr text on this site.

**Comment by martindholmes** [comment] 2021-07-31 17:38
I can confirm that this happens when tokenizing ltr text as well, so it's just a regular bug. I've added test data in test/apostrophes.html and we can work with that to figure out the problem. I'll change the description of the issue to reflect the situation.

**Comment by joeytakeda** [comment] 2021-08-15 03:56
After a brief email discussion with @martindholmes , we think that the problem is likely due to the `\p{L}` part of the word tokenizing regex here:

https://github.com/projectEndings/staticSearch/blob/d3162b6f85b2363b9b1cf9d2b73721e86ff8a738/xsl/tokenize.xsl#L103

That should probably be expanded to include the Unicode non-spacing marks character class to the token regex: https://www.compart.com/en/unicode/category/Mn

Assigning to @martindholmes , since he has added the test and will be able to test edge cases more effectively than me (woefully monolingual).

**Comment by martindholmes** [comment] 2021-08-15 22:18
@wsalesky I've just committed a fix that works for my limited testing to the dev branch. Is there any chance you could test with your data? If it's fixed, then great, but if it's not, can you give me a couple of words from your corpus that are split where they shouldn't be, so I can incorporate those into the tests and revise the fix?

**Comment by wsalesky** [comment] 2021-08-17 14:26
@martindholmes It works! Thanks for your help! By the way here is the site using the search, just went live last week: http://medievalmideast.org/

**Comment by martindholmes** [comment] 2021-08-17 15:33
@wsalesky Great! I'm really happy to be able to see your site, too. Can we link to it from our documentation?

**Comment by wsalesky** [comment] 2021-08-17 15:52
@martindholmes Yes you can link to it from the documentation.

**Comment by martindholmes** [comment] 2021-08-17 15:56
Thanks! I'll close this now.

**Closed by martindholmes** 2021-08-17 15:56 UTC
Labels: bug
