### ISSUE TITLE
Make wildcard search not case sensitive

### ISSUE THREAD

**Issue by martinantonmueller** [projectEndings/staticSearch#188] opened 2022-01-24 09:06 UTC
How can I get the wild card search to be case insensivite? I.e. "hauptmann*" and "Hauptmann*" should have the same results.

**Comment by martinantonmueller** [comment] 2022-01-24 09:42
I've asked: https://github.com/projectEndings/staticSearch/issues/188

**Comment by joeytakeda** [comment] 2022-01-24 18:49
I just did a look back through the issues and I can only find evidence that we wanted wildcards to be case insensitive:

> We could also substantially reduce the weight by deciding that all wildcard matches are case-insensitive (as they are in this current implementation), so that file would be smaller. I'm inclined to go that way.

https://github.com/projectEndings/staticSearch/issues/48#issuecomment-649140268

So I think this is really a bug, especially since I can't think of any reason why they ought to be case sensitive.

**Comment by martindholmes** [comment] 2022-01-24 19:01
Agreed, and I think the problem is possibly at line 915 and 916 of StaticSearch.js:

~~~~~
let re = this.wildcardToRegex(strInput);
let matches = [...this.wordString.matchAll(re)];
~~~~~

and in wildcardToRegex:

`let re = new RegExp('\\|(' + strRe + ')\\|', 'g');`

we don't set 'i' for case-insensitive. That might be a very simple fix. I'm going to test now.

**Comment by martindholmes** [comment] 2022-01-24 19:15
@joeytakeda Pull request is in. Only one character changes. :-)

**Comment by joeytakeda** [comment] 2022-01-24 19:20
Works for me, so I've now merged it in. @martinantonmueller : the dev branch should now have case insensitive wildcards--could you let us know if that solves the issue and then we'll close this ticket. Thanks!

**Comment by martinantonmueller** [comment] 2022-01-24 20:42
Thank you for acting so quick! We will look into it and get back as soon as possible!

**Comment by martinantonmueller** [comment] 2022-01-25 10:28
I was told that currently only releases are used as basis for our project. So I can't test the dev-branch but I believe your fix should work anyhow. Will there be a smaller release, i.e. 1.3.1 or do you have an estimate when 1.4 will be ready? Thank you once again for acting so quickly!

**Comment by martindholmes** [comment] 2022-01-25 16:52
@martinantonmueller We're aiming to get a release out in the next couple of weeks. But if you're unable to test the dev branch, I'll close the ticket, since we have multiple projects which build with the dev branch and we can test in those.

**Closed by martindholmes** 2022-01-25 16:52 UTC
