### ISSUE TITLE
Update to Saxon 11

### ISSUE THREAD

**Issue by joeytakeda** [projectEndings/staticSearch#264] opened 2023-02-08 05:47 UTC
Saxon 11 has been around for a while, so we should update this in dev.

**Comment by martindholmes** [comment] 2023-02-08 17:59
I tested on Linux and all is fine, but on Windows we get an error:

config:
     [echo] Creating configuration file...
     [java] Creating configuration file from file:///C:/Users/mholmes/temp/staticSearch/configTest.xml
     [java] Version string for this build: 7efe645
     [java] Error in xsl:result-document/@href on line 309 column 133 of create_config_xsl.xsl:
     [java]   SXRD0001  Resolved URL is malformed. Caused by java.net.MalformedURLException: unknown protocol: c
     [java]   In template rule with match="/" on line 284 of create_config_xsl.xsl
     [java] Resolved URL is malformed

I don't have time to look at this now, but I think it'll be an easy fix.

**Comment by martindholmes** [comment] 2023-03-07 21:29
This is now complete; if nothing anomalous shows up in the next little while, we can close it.

**Comment by martindholmes** [comment] 2024-04-18 16:07
@joeytakeda I think we should probably go to version 12 now, don't you think? I don't know of any potential issues between 11 and 12, do you?

**Closed as completed** 2024-05-10 17:55 UTC
Labels: enhancement
