### ISSUE TITLE
Config file generation bug

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#219] opened 2022-02-15 21:49 UTC
Setting up a search-in context like this:

`<context match="main/h2 | div[matches(@class, '(poem)|(drama)|(cycle)')]/h2[@data-el = 'head']" label="Poem title"/>`

generates a config file with a series of ill-formed xsl:if clauses, because the pipe in the regex is assumed to be delimiting separate match contexts:

~~~~~
<xsl:if test="self::div[matches(@class, '(poem)">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx2'"/>
         </xsl:if>
         <xsl:if test="self::(drama)">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx2'"/>
         </xsl:if>
         <xsl:if test="self::(cycle)')]/h2[@data-el = 'head']">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx2'"/>
         </xsl:if>
~~~~~

Easy to work around, but probably also fixable.

**Comment by joeytakeda** [comment] 2022-02-23 23:41
This is really interesting and, as these kind of things often do, revealed a whole tangle of issues that are neither particularly easy nor easily ignorable, I think...

Those set of `<xsl:if>`s are generated here:

https://github.com/projectEndings/staticSearch/blob/aa33befbf75b56cd2ba9ac2e95b79aa2ab88095a/xsl/create_config_xsl.xsl#L676-L702

This follows the same pattern as the `<rule>`s for weights: we create a single template with all of the matches strung together and, for every node matched, we then use a series of ifs to determine which label/context attributes (in this case) or weight attribute (in the case of `<rule>`) that element should bear. 

The reason we strung those together rather than make individual templates for each rule or context is because we wanted to avoid ambiguous rule matches. That's been the way it's been done since the beginning more or less, but now that I look into it, I'm honestly quite surprised that it actually works and hasn't broken before since that series of ifs could quite easy create duplicate attributes in cases where an element matches multiple contexts/rules:

E.g. if you had something like this:


```
<context match="p" label="Paragraphs"/>
<context match="p[contains-token(@class,'citations')] | cite" label="Citations"/>
```

The config would contain:

```
 <xsl:template match="p | p[contains-token(@class,'citation')]"
                 priority="1"
                 mode="contextualize">
      <xsl:if test="$verbose">
         <xsl:message>Template #contextualize: Adding @ss-ctx flag to <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*" mode="#current"/>
         <xsl:if test="self::p">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx4'"/>
         </xsl:if>
         <xsl:if test="self::p[contains-token(@class,'citation')]">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx3'"/>
         </xsl:if>
         <xsl:apply-templates select="node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>
```

I would have thought that this should be an error, but Saxon happily processes it, yielding ` <p ss-ctx="true" ss-ctx-id="ssCtx3">`. Switching the order of those `<xsl:if>s` changes the result: `<p ss-ctx="true" ss-ctx-id="ssCtx4">` So that leads me to believe that Saxon silently ignores when duplicate attributes are produced in this way and just takes the last one constructed. That seems to me like a rather unstable quirk rather than a feature, so I'd worry that it might come back to haunt us.

All of this is to say: this certainly is fixable and should be fixed even though it will be a bit tricky. I think we should make it so that each rule / context (i.e. `*[@match]`) gets its own `<xsl:template>` in the config; however, we'll need to make some clear decisions on how to deal with ambiguous pattern matches.

My thought is:

* For rules, it makes no sense to have more than one weight, so we should set the precedence to 1 for all `<rule>` templates and simply let Saxon work out the precedence and fail when there are multiple matches (i.e. https://www.saxonica.com/html/documentation10/xsl-elements/mode.html). It would be nice if we could figure out how to integrate that kind of check to the diagnostics / validation (#212) 
* For contexts, I think it does make sense for a single element to have multiple contexts so I don't think we should fail on multiple matches. There's a few ways I can think about doing that (multiple generated modes or possibly`<xsl:next-match/>`), but before I go into that, we should probably discuss whether an element can have multiple contexts.

**Comment by joeytakeda** [comment] 2022-02-23 23:43
Addendum: here's a minimal config for replicating what I talk about re: the contexts for the test set:

```
<config xmlns="http://hcmc.uvic.ca/ns/staticSearch" version="2">
    <params>
        <searchFile>test/search.html</searchFile>
        <versionFile>test/VERSION</versionFile>
        <recurse>true<!--Need to set recurse to true for the test--></recurse>
        <phrasalSearch>true</phrasalSearch>
        <wildcardSearch>true</wildcardSearch>
        <createContexts>true</createContexts>
        <resultsPerPage>5</resultsPerPage>
        <minWordLength>2</minWordLength>
        <!--NOTE: If phrasalSearch is set to TRUE, then
        maxContexts prop will be ignored-->
        <maxKwicsToHarvest>5</maxKwicsToHarvest>
        <maxKwicsToShow>5</maxKwicsToShow>
        <totalKwicLength>15</totalKwicLength>
        <kwicTruncateString>...</kwicTruncateString>
        <stopwordsFile>test/test_stopwords.txt</stopwordsFile>
        <dictionaryFile>xsl/english_words.txt</dictionaryFile>
        <outputFolder>ssTest</outputFolder>
    </params>
    <contexts>
        <context match="p" label="Paragraphs"/>
        <context match="p[contains-token(@class,'citation')]" label="Citations"/>
    </contexts>
</config>
```

**Comment by joeytakeda** [comment] 2022-05-30 21:40
Set this to bug and release 2.0, since this is something that should be fixed.

**Comment by joeytakeda** [comment] 2023-03-22 17:52
The problem is primarily the order of operations: if an element has multiple contexts, those need to be strung together; probably `<xsl:next-match/>` with a tunnelled parameter and a low priority generic template that applies the attribute to the element.

**Comment by joeytakeda** [comment] 2023-03-22 21:23
I've been thinking about this a bit more, and I think we have to come up with a policy decision in terms of precedence when it comes to these rules; this is also related to #246 where the cleaning step is done first and thus removes information that may be useful in another stage.

Right now, we pass each document through a multi-stage process (using modes) in this order:

* Cleaning
* Weighing
* Contextualizing
* Tokenizing

As we note in #246 , cleaning used to be first when we cared more about processing the entire collection at once; that doesn't matter anymore, though, since we now do it document by document. However, I think we have some other issues to work out when it comes to the precedence of the actual rules:

Let's say you want:

* `<p>` to have a weight of 3
* `p[preceding-sibling::cite]` to be erased
* `<p>`s to be contexts with a label of "Paragraph"
* `blockquote/p` to have a context of "Blockquote Paragraph", but a weight of 1

That would be expressed in the configuration as something like:

```xml
<rules>
     <rule match="p" weight="3"/>
     <rule match="blockquote/p" weight="1"/>
     <rule match="p[preceding-sibling::cite]" weight="0"/>
</rules>
<contexts>
     <context match="p" label="Paragraph"/>
     <context match="blockquote/p" label="Blockquote Paragraph"/>
</contexts>
```
And produces the follow `config.xsl` (trimmed for brevity):

```xslt
<xsl:template match="p | blockquote/p" priority="1" mode="clean">
      <xsl:if test="$verbose">
         <xsl:message>Template #clean: retaining <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*|node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>
   <xsl:template match="p[preceding-sibling::cite]" priority="1" mode="clean">
      <xsl:if test="$verbose">
         <xsl:message>Template #clean: Deleting <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
   </xsl:template>
   <xsl:variable name="ssContextMap" as="map(*)?">
      <xsl:map>
         <xsl:map-entry key="'Paragraph'" select="'ssCtx1'"/>
         <xsl:map-entry key="'Blockquote Paragraph'" select="'ssCtx2'"/>
      </xsl:map>
   </xsl:variable>
   <xsl:template match="p | blockquote/p" priority="1" mode="contextualize">
      <xsl:if test="$verbose">
         <xsl:message>Template #contextualize: Adding @ss-ctx flag to <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*" mode="#current"/>
         <xsl:if test="self::p">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx1'"/>
         </xsl:if>
         <xsl:if test="self::blockquote/p">
            <xsl:attribute name="ss-ctx" select="'true'"/>
            <xsl:attribute name="ss-ctx-id" select="'ssCtx2'"/>
         </xsl:if>
         <xsl:apply-templates select="node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>
   <xsl:template match="p" priority="1" mode="weigh">
      <xsl:if test="$verbose">
         <xsl:message>Template #weigh: Adding @data-weight to <xsl:value-of select="local-name(.)"/>
         </xsl:message>
      </xsl:if>
      <xsl:copy>
         <xsl:apply-templates select="@*" mode="#current"/>
         <xsl:if test="self::p">
            <xsl:attribute name="ss-wt" select="3"/>
         </xsl:if>
         <xsl:apply-templates select="node()" mode="#current"/>
      </xsl:copy>
   </xsl:template>

```

A few things to note:

1. In clean: the `p`s we know have some sort of weighting (so `p` and `blockquote/p`) and the unwanted `p` (`p[preceding-sibling::cite]`) are separate templates and produce a ambiguous rule error (which is just a warning) — so, in other words, the cleaning step splits depending on if there's some reason to keep the p, and then lets Saxon determine the precedence of retaining vs deleting.
3. In weight: the `blockquote/p`, since it has a weight of 1, is just dropped (that's a bug) and thus all `p`s are given a weight of 3 
4. In contextualize: the `p` and `blockquote/p` rules are strung together to avoid ambiguity, but it is still ambiguous: in the end, the `blockquote/p` only bears the single context ('Blockquote Paragraph') and not the 'Paragraph' context, since the contexts are not cumulative (and the attributes silently overwrite each other) — in other words, we determine precedence by the order of the `<context>`s 

While it makes sense for contexts to be multiple things (and, in fact, the code already handles that), it does not make sense for something to have multiple weights

I think we could simplify this quite significantly _if_ we can figure out what to do when there is ambiguity—I can think of a few options:

1. Every `<rule>` and `<context>` map 1-1 to an `<xsl:template>`, all of which have the same precedence and users should ensure they don't have ambiguous rules (i.e. watch for warnings, testing, etc) 
2. Same as above, but we set the `<xsl:mode>` instruction to fail on ambiguous rule matches
3. Every `<rule>` and `<context>` map 1-1 to an `<xsl:template>`,  but their precedence is based on the order they are specified (i.e. later overrides earlier) 

With 1 & 2, we still have the same problem as in #246 that an earlier stage needs to know about a later stage in order to determine if it can be erased, but that cleaning stage could come later (if we wanted it to)

With 3, I don't think we need to do things in multiple passes — instead, we use a `<xsl:next-match/>` approach to iterate through the elements, one by one, to determine what we need to do with the element as soon as we get to it.

**Comment by joeytakeda** [comment] 2023-09-13 18:20
Discussing with MH: We should try and use accumulators for this, which would allow us to investigate any of the issues regarding precedence (in other words, each `*[@match]` becomes an xsl:accumulator-rule rather than a template). Then, we investigate each node, construct a data structure that gives us information about a particular node (via the accumulator), and then make a decision (probably hived off to a new function) on what we should do with that node.

**Comment by joeytakeda** [comment] 2023-09-13 21:11
So after further discussion with MH, it looks like accumulators probably won't work for us as accumulator-rules don't have any graceful fallback for conflicts in precedence. 

To summarize the main problem is that rules of the same type (i.e. weighting or context rules) may address the same element; we want to be able to figure out which of these should take precedence; we don't want to try and make an arbitrary decision about this, given that the XSLT spec defines mechanisms for working out conflict resolution. However, we want to be able to know precisely what order these templates are being matched, since in some instances (like for contexts) we want to accumulate all the values rather than have the last taking precedence over the first.

The problem is that if we did something like assigning a priority based on document order, we'd end up overriding the built-in precedence rules. E.g.: consider this config

```xml
<rules>
     <rule match="blockquote/p" weight="1"/>
     <rule match="p[preceding-sibling::cite]" weight="0"/>
     <rule match="p" weight="3"/>
</rules>
```

If we assigned priorities based on document order, we'd have something like:

```xml

<xsl:template match="blockquote/p" priority="3">1</xsl:template>
<xsl:template match="p[preceding-sibling::cite]" priority="4">0</xsl:template>
<xsl:template match="p" priority="5">3</xsl:template>
```
This would make every paragraph a 3, since the basic `p` match would always apply before the more specific `@match`es.

So rather than try and work out precedence based on order, I think we should simply allow the processor to following the XSLT spec and compute the priority of the template matches for us; we can work around the problem of ambiguity, however, by using [xsl:next-match](https://www.w3.org/TR/xslt-30/#element-next-match), which,  according to the XSLT Spec, "considers all other template rules of lower [import precedence](https://www.w3.org/TR/xslt-30/#dt-import-precedence) and/or priority, and **also declarations of the same precedence and priority that appear earlier in [declaration order](https://www.w3.org/TR/xslt-30/#dt-declaration-order)**" (emphasis mine).

What I'm thinking here is the following:

1. We create template with priority of 3 that sets up a map of data to be passed through each element; this should match all of the patterns specified in by the config (i.e. the distinct values of `*/@match`)
3. We transform each `*[@match]` element in the config (rule, context, et cetera) into an `<xsl:template>` with priority 2, which will allow Saxon to use the XSLT-defined rules for determining precedence  
4. We suppress errors and warnings about multiple matches on the `xsl:mode`
5. We create a template with priority 1 that reads the now populated data map and determines whether to remove it or decorate it with attributes.

**Comment by joeytakeda** [comment] 2023-09-13 21:21
Following up on the above, here is what I think the compiled XSLT should look like (i.e. what we should produce in `create_config`) — does this seem right to you @martindholmes ? 

### Input HTML
```html
<body>
    <menu>
        <div>Stuff that should be unchanged.</div>
    </menu>
    <section>
        <p id="p1">A basic paragraph</p>
        <blockquote>
            <p id="p2">A famous quotation</p>
            <cite>Shakespeare</cite>
            <p id="p3">Unimportant information (should be removed)</p>
        </blockquote>
        <p>This is an address line
            <span class="address">742 Evergreen Terrace</span>
        </p>
    </section>
</body>
```


### Config
```xml
   <config>
    <!-- A bunch of params etc -->
        <rules>
            <rule match="p" weight="3"/>
            <rule match="blockquote/p | p[descendant::span[@class='address']]" weight="1"/>
            <rule match="p[preceding-sibling::cite]" weight="0"/>
        </rules>
        <contexts>
            <context match="p" label="Paragraph"/>
            <context match="blockquote/p" label="Blockquote"/>
            <context match="p[descendant::span[@class='address']]" label="Address"/>
        </contexts>
    </config>
```

### Config XSL

_NB: This isn't exactly what the config XSL will look like of course, since there'll be all sorts of other attributes to figure out, but this is the gist of it_

```xsl
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    xmlns:map="http://www.w3.org/2005/xpath-functions/map"
    xmlns:array="http://www.w3.org/2005/xpath-functions/array"
    exclude-result-prefixes="#all"
    version="3.0">
    <xsl:mode 
        warning-on-multiple-match="false"
        on-no-match="shallow-copy"/>
    
    <!--[...many many parameters, trimmed for brevity ... ]-->

    <!--Map of contexts generated from the config-->
    <xsl:variable name="contextMap" as="map(*)">
        <xsl:map>
            <xsl:map-entry key="'Paragraph'">ssCtx1</xsl:map-entry>
            <xsl:map-entry key="'Blockquote'">ssCtx2</xsl:map-entry>
            <xsl:map-entry key="'Address'">ssCtx3</xsl:map-entry>
        </xsl:map>
    </xsl:variable>
    
    <!--Distinct values of all `@match` attributes to set up the map
        (Note this may still means duplicates, but that's fine) -->
    <xsl:template priority="3"
        match="p |
               blockquote/p | 
               p[descendant::span[@class='address']] |
               p[preceding-sibling::cite] |
               p[descendant::span[@class='address']]">
        <xsl:next-match>
            <!--Create the basic data map as a tunnelled param-->
            <xsl:with-param name="data"
                tunnel="yes" as="map(*)" 
                select="map{
                   'weights': (),
                   'contexts': ()
                }"/>
        </xsl:next-match>
    </xsl:template>
    
<!--#################### RULES -->
    <!--##### RULE 1-->
    <xsl:template match="p" priority="2">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:next-match>
            <xsl:with-param name="data" 
                tunnel="yes" 
                select="map:put($data, 'weights', ($data('weights'), 3))"/>
        </xsl:next-match>
    </xsl:template>
    <!--##### RULE 2-->
    <xsl:template match="blockquote/p | p[descendant::span[@class='address']]" priority="2">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:next-match>
            <xsl:with-param name="data"
                tunnel="yes" 
                select="map:put($data, 'weights', ($data('weights'), 1))"/>
        </xsl:next-match>
    </xsl:template>
    <!--##### RULE 3-->
    <xsl:template match="p[preceding-sibling::cite]" priority="2">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:next-match>
            <xsl:with-param name="data" 
                tunnel="yes"
                select="map:put($data, 'weights', ($data('weights'), 0))"/>
        </xsl:next-match>
    </xsl:template>
    
<!--#################### CONTEXTS -->   
    <!--##### CONTEXT 1-->
    <xsl:template match="p" priority="2">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:variable name="ctxId" select="$contextMap('Paragraph')"/>
        <xsl:next-match>
            <xsl:with-param name="data" 
                tunnel="yes" 
                select="map:put($data, 'contexts', ($data('contexts'), $ctxId))"/>
        </xsl:next-match>
    </xsl:template>
    <!--##### CONTEXT 2-->
    <xsl:template match="blockquote/p" priority="2">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:variable name="ctxId" select="$contextMap('Blockquote')"/>
        <xsl:next-match>
            <xsl:with-param name="data"
                tunnel="yes" 
                select="map:put($data, 'contexts', ($data('contexts'), $ctxId))"/>
        </xsl:next-match>
    </xsl:template>
    <!--##### CONTEXT 3-->
    <xsl:template match="p[descendant::span[@class='address']]" priority="2">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:variable name="ctxId" select="$contextMap('Address')"/>
        <xsl:next-match>
            <xsl:with-param name="data"
                tunnel="yes" 
                select="map:put($data, 'contexts', ($data('contexts'), $ctxId))"/>
        </xsl:next-match>
    </xsl:template>

<!--#################### Template that determines
                         how to handle the element (using
                         the same distinct matches as before) -->
    
    <xsl:template priority="1"
        match="p |
        blockquote/p | 
        p[descendant::span[@class='address']] |
        p[preceding-sibling::cite] |
        p[descendant::span[@class='address']]">
        <xsl:param name="data" tunnel="yes" as="map(*)"/>
        <xsl:variable name="weights" select="$data?weights" as="xs:integer*"/>
        <xsl:variable name="contexts" select="$data?contexts" as="xs:string*"/>
        <xsl:choose>
            <!--If nothing came from the data map (which shouldn't happen),
                then simply go to default processing-->
            <xsl:when test="empty($weights) and empty($contexts)">
                <xsl:next-match/>
            </xsl:when>
            <!--If it has been specified as 0, then delete-->
            <xsl:when test="exists($weights) and $weights[1] = 0"/>
            <!--Otherwise, copy out the element and add the attributes
                when necessary -->
            <xsl:otherwise>
                <xsl:copy>
                    <xsl:where-populated>
                        <!--Use the first weight since it
                            comes from the rule with the highest
                            precedence (which may mean specificity
                            OR order in the config -->
                        <xsl:attribute name="weight" 
                            select="$weights[1]"/>
                    </xsl:where-populated>
                    <xsl:where-populated>
                        <!--Join all of the contexts together,
                            in which order doesn't matter-->
                        <xsl:attribute name="contexts"
                            select="string-join($contexts,' ')"/>
                    </xsl:where-populated>
                    <!--And process normally-->
                    <xsl:apply-templates select="@*|node()"/>
                </xsl:copy>
            </xsl:otherwise>
        </xsl:choose>
    </xsl:template>
    
    <!--We can still have default templates for some of the
        basic cleaning, which will be applied after all of
        the other steps (which resolves 
        https://github.com/projectEndings/staticSearch/issues/246) -->
    <xsl:template match="span">
        <xsl:apply-templates/>
    </xsl:template>
</xsl:stylesheet>
```

### Output HTML

```html
<body>
    <menu>
        <div>Stuff that should be unchanged.</div>
    </menu>
    <section>
        <p weight="3" contexts="ssCtx1" id="p1">A basic paragraph</p>
        <blockquote>
            <p weight="1" contexts="ssCtx2 ssCtx1" id="p2">A famous quotation</p>
            <cite>Shakespeare</cite>
            
        </blockquote>
        <p weight="1" contexts="ssCtx3 ssCtx1">This is an address line
            742 Evergreen Terrace
        </p>
    </section>
</body>
```

**Comment by joeytakeda** [comment] 2023-09-14 02:12
Started work on this in `iss219-config` — lots of changes so far and things seem to be working, but tests are failing

**Comment by joeytakeda** [comment] 2023-11-01 18:08
Discussion with MH today—the tunnelled map approach looks like it will work, but processing for what we should do with multiple matches will need to be expanded:

1. First, the branch as it is now has the wrong order: default values for elements must be populated first in a higher priority (i.e. `div` being a context should get a `true()` as its first value for contextMap, but should have other user-configured values appended
2. Policy decision is to follow Saxon's prioritization: use the **last** value in a sequence in the data map (i.e. weight: 0, 4, 10 would be a weight of 10)
3. We still need to consider what conditions may cause warnings or errors if there are conflicts: i.e. does it make sense for something to have a contextID but be user-specified as not a context.

**Closed** 2024-05-10 17:49 UTC
Labels: bug
