### ISSUE TITLE
Need to add a splash-screen for "loading" for complex search pages

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/staticSearch#156] opened 2021-05-13 17:00 UTC
The addition of feature filters has allowed for situations where the page is slow to initialize, especially when a search is being run on load. This should work like the "Searching" message, but display right away, and be hidden either when "Searching" happens, or when the page is ready to use.

**Comment by martindholmes** [comment] 2021-08-17 18:27
I've done a simple implementation of this in branch issue-156-splash, and set the Despatches project build to use it (Despatches has lots of typeahead filters). Once we've tested there, we can test on other smaller projects to see if it's unnecessarily intrusive.

**Comment by joeytakeda** [comment] 2021-08-18 21:00
Initial implementation is now merged into `dev` and will test with other projects.

**Comment by joeytakeda** [comment] 2021-08-18 23:05
In working on the optimization for the filters (more on that soon), I discovered a bug with the current implementation of the splash screen (i.e. in the Jenkins version of ColDesp). In Safari, triggering a search from the URL does not remove the loading cursor or "SEARCHING" popup. I'm not sure why it's only happening in Safari; there's no console.log warnings or errors that indicate why it's happening—I'll investigate.

**Comment by martindholmes** [comment] 2021-08-18 23:23
Confirmed in Safari 14.1.2: the splash screen goes away, but the "Searching" message doesn't. Very odd. Have to get this fixed for 1.4, for sure. If you don't figure it out quickly, raise a separate bug.

**Comment by joeytakeda** [comment] 2021-09-08 23:42
One thing I've noticed about the Loading message is that it happens immediately for all projects, even those without feature filters, and blocks use of those pages until everything is loaded. That seems like a regression to me—before, the user never needed to know care about (or wait for) things being downloaded in the background, but now the page is blocked until all of the filter JSONs are loaded. 

Since this loading screen is only necessary for the feature filters, I propose that we only show the splash screen iff a project has feature filters configured. Either we could do this in the JS by adding a test for the existence of feature filters to the block that enables the splash:

https://github.com/projectEndings/staticSearch/blob/2340213e4aed1603efe320459adc36832da6b4c9/js/StaticSearch.js#L63-L70

Or we could do this in the XSLT by adding the splash div iff there are feature filters:

https://github.com/projectEndings/staticSearch/blob/2340213e4aed1603efe320459adc36832da6b4c9/xsl/makeSearchPage.xsl#L496-L499

Thoughts?

**Comment by martindholmes** [comment] 2021-09-09 15:21
Agreed. It only usually flashes into view and disappears, but there is no need for it. I think the XSLT version makes the most sense, so I've just implemented that in the dev branch. Let's watch it roll out to the projects and see if we're happy with it.

**Comment by martindholmes** [comment] 2021-09-09 20:01
My testing suggests this is working well with the existing projects. Shall we close this now?

**Comment by joeytakeda** [comment] 2021-10-03 01:22
Apologies for the delayed reply, but yes, this looks good to me (confirming on projects that it works). I'll close this now.

**Closed by joeytakeda** 2021-10-03 01:22 UTC
Labels: bug, release-blocker
